apiVersion: v1
kind: Namespace
metadata:  
  labels:
    app: kubedr
  name: kubedr

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedr
  namespace: kubedr

---

# Grant readonly access to resources.
# N.B. This includes access to secrets which could include sensitive information even
# though secrets aren't actually secret.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedr-readonly
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"]

- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list"]

- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedr-read-only
subjects:
- kind: ServiceAccount
  name: kubedr
  namespace: kubedr
roleRef:
  kind: ClusterRole
  name: kubedr-readonly
  apiGroup: rbac.authorization.k8s.io
