apiVersion: v1
kind: Namespace
metadata:  
  labels:
    app: kubepilot
  name: kubepilot

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepilot
  namespace: kubepilot

---

# Grant readonly access to resources.
# N.B. This includes access to secrets which could include sensitive information even
# though secrets aren't actually secret.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepilot-readonly
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"]

- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list"]

- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepilot-read-only
subjects:
- kind: ServiceAccount
  name: kubepilot
  namespace: kubepilot
roleRef:
  kind: ClusterRole
  name: kubepilot-readonly
  apiGroup: rbac.authorization.k8s.io
